---
- name: Download Spark code and decompress it
  unarchive: src=http://apache.rediris.es/spark/spark-1.6.2/spark-1.6.2-bin-hadoop2.6.tgz dest=/opt/ copy=no creates=/opt/spark-1.6.1-bin-hadoop2.6 copy=no

- name: Create symbolic link to spark
  file: src=/opt/spark-1.6.1-bin-hadoop2.6 dest=/opt/spark state=link

- name: update PATH environment variable
  copy: dest=/etc/profile.d/spark.sh content="export PATH=$PATH:/opt/spark/bin\nexport SPARK_HOME=/opt/spark"
